# Generated by Django 3.2.8 on 2021-10-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Fullstack', 'Fullstack'), ('Frontend', 'Frontend')], max_length=20),
        ),
    ]
