# Generated by Django 3.2.8 on 2021-10-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Fullstack', 'Fullstack'), ('Backend', 'Backend')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], max_length=20),
        ),
    ]
