# Generated by Django 3.2.8 on 2021-11-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_auto_20211031_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Fullstack', 'Fullstack'), ('Backend', 'Backend')], max_length=20),
        ),
    ]
