# Generated by Django 3.2.8 on 2021-11-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0011_auto_20211101_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Fullstack', 'Fullstack'), ('Frontend', 'Frontend'), ('Backend', 'Backend')], max_length=20),
        ),
    ]
