# Generated by Django 3.2.8 on 2021-11-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0015_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Fullstack', 'Fullstack'), ('Backend', 'Backend')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
